using Microsoft.EntityFrameworkCore;
using OAuth2.WebApi.Core.Entities;

namespace OAuth2.WebApi.Core.DB;

/// <summary>
/// DataContext Class, add as a service to program.cs
/// </summary>
public class DataContext : DbContext
{
    public DataContext(DbContextOptions options) : base(options)
    {
    }

    public DbSet<AppUser> Users { get; set; }

    //we are not putting the DBSet for Photos
    //Photos will be pulled via Users
    //setup a relationships in photos and apply the Table attriute to it

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        //AppUser has guid that needs to be autogenerated for insert
        //This isn't working, in AppUser create the guid
        /*
        modelBuilder.Entity<AppUser>()
        .Property(x => x.Guid)
        .ValueGeneratedOnAdd();
        */

        //make DisplayName Unique
        modelBuilder.Entity<AppUser>(entity =>
        {
            entity.HasIndex(e => e.DisplayName).IsUnique();
        });
    }
}
